In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(4,)


In [8]:
b = np.array([[1,2,3,4], [5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
print(b.shape)

(2, 4)


In [9]:
b.T


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [10]:
np.dot(b,b.T)

array([[ 30,  70],
       [ 70, 174]])

In [12]:
np.random.randint(60,100,10)


array([98, 77, 63, 70, 76, 88, 67, 92, 88, 84])

In [17]:
matrix = np.random.randint(60,100,(5,5))

In [18]:
print(matrix)

[[66 98 73 98 83]
 [67 88 77 69 67]
 [60 85 70 60 95]
 [64 79 75 71 64]
 [69 64 83 94 89]]


In [19]:
#find max element from numpy array
np.max(matrix)

98

In [20]:
#minimum element
np.min(matrix)

60

In [21]:
a = np.array([0,1,24,3,4,8,4])

In [22]:
np.argmin(a)

0

In [23]:
np.argmax(a)

2

In [24]:
np.unique(a)

array([ 0,  1,  3,  4,  8, 24])

In [25]:
print(np.unique(a, return_counts = True))

(array([ 0,  1,  3,  4,  8, 24]), array([1, 1, 1, 2, 1, 1]))


In [31]:
b = np.array([22,4524,42,42,42,23, 34, 87,98,56,67,45,345])


In [32]:
print(b[0])
print(b[-1])


22
345


In [28]:
#program to find the number with highest frequency in the given array

In [33]:
b= np.unique(b,return_counts=True)

In [34]:
print(b)

(array([  22,   23,   34,   42,   45,   56,   67,   87,   98,  345, 4524]), array([1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1]))


In [37]:
print(b[0][np.argmax(b[1])])

42


In [39]:
#slicing arrays
matrix

array([[66, 98, 73, 98, 83],
       [67, 88, 77, 69, 67],
       [60, 85, 70, 60, 95],
       [64, 79, 75, 71, 64],
       [69, 64, 83, 94, 89]])

In [40]:
matrix[2:4, 1: 3]

array([[85, 70],
       [79, 75]])

In [41]:
matrix[0][0]

66